// App.js
import Amplify from 'aws-amplify';
import awsconfig from './src/aws-exports'; // The configuration file generated by Amplify
import React from 'react';
import { View, Text } from 'react-native';
import realm from './src/models/ChatModels';

Amplify.configure(awsconfig);
const Stack = createStackNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator initialRouteName="Home">
        <Stack.Screen name="Home" component={HomeScreen} />
        <Stack.Screen name="InstagramLogin" component={InstagramLoginScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

